name: BuildRoot

on:
  push:
    tags:
      - 'v*'
env:
  PROJECT_NAME: "key_value_pair_storage"
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Clone source code
      run: |
        git clone https://github.com/Feupos/buildroot-kvpstorage /opt/buildroot-kvpstorage
        git clone https://github.com/buildroot/buildroot.git /opt/buildroot
        cd /opt/buildroot

    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get install -y make gcc g++ unzip git bc python device-tree-compiler mtd-utils

    - name: Bulid
      run: |
        mkdir /opt/artifacts
        cd /opt/buildroot
        git checkout ${{github.event.inputs.branches-tags}}
        git pull origin ${{github.event.inputs.branches-tags}}

        echo '---start make---'
        make BR2_EXTERNAL=/opt/buildroot-kvpstorage qemu_arm_versatile_kvpstorage_defconfig
        make
        cp -r /opt/buildroot/output/images /opt/artifacts

    - name : Upload buildroot-kvpstorage-${{github.event.inputs.branches-tags}}-
      uses: actions/upload-artifact@master
      with:
        name: buildroot-kvpstorage-${{github.event.inputs.branches-tags}}
        path: /opt/artifacts